openapi: 3.0.0
info:
  description: This is the swagger API for Digital_Two_D_Seismic _Section
  version: 1.0.0
  title: Digital_Two_D_Seismic _Section
  termsOfService: http://swagger.io/terms/
  contact:
    email: darren.mannuela@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- description: Digital_Two_D_Seismic _Section
  url: http://localhost:8080/api/v1
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/DarrenMannuela/Digital_Two_D_Seismic_Section/1.0.0
tags:
- name: Afe
  description: All endpoints related to get Digital_Two_D_Seismic _Section AFE
- name: Workspace
  description: All endpoints related to Digital_Two_D_Seismic _Section Workspace
- name: Digital Two D Seismic  Section
  description: All endpoints related to Digital_Two_D_Seismic _Section
- name: Digital Two D Seismic  Section Dummy Data
  description: All endpoints related to Digital_Two_D_Seismic _Section
paths:
  /Digital-Two-D-Seismic -Section-afe:
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Digital_Two_D_Seismic _Section AFE
      responses:
        '200':
          description: get Digital_Two_D_Seismic _Section AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Digital Two D Seismic  Section
              user_id: 1
    post:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Post a new Digital_Two_D_Seismic _Section AFE
      description: Create a new Digital_Two_D_Seismic _Section AFE data
      requestBody:
        required: true
        description: Request body to create Digital_Two_D_Seismic _Section AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Two_D_Seismic _Section'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Digital Two D Seismic  Section
            user_id: 1
      responses:
        '200':
          description: Digital_Two_D_Seismic _Section data is added
          content:
            application/json:
              example:
                message: The Digital_Two_D_Seismic _Section AFE data was successfully
                  added
  /Digital-Two-D-Seismic -Section-afe/{afe}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Digital_Two_D_Seismic _Section data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Digital_Two_D_Seismic _Section AFE
      responses:
        '200':
          description: get Digital_Two_D_Seismic _Section AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Digital Two D Seismic  Section
              user_id: 1
    put:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Digital_Two_D_Seismic _Section AFE data
      description: Update a new Digital_Two_D_Seismic _Section data
      requestBody:
        required: true
        description: Request body to update Digital_Two_D_Seismic _Section AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Two_D_Seismic _Section'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Digital Two D Seismic  Section
            user_id: 1
      responses:
        '200':
          description: Digital_Two_D_Seismic _Section data is completely updated
          content:
            application/json:
              example:
                message: The Digital_Two_D_Seismic _Section AFE data is completely
                  updated
    patch:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Digital_Two_D_Seismic _Section AFE data
      description: Update a new Digital_Two_D_Seismic _Section data
      requestBody:
        required: true
        description: Request body to update Digital_Two_D_Seismic _Section AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Two_D_Seismic _Section'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Digital Two D Seismic  Section
            user_id: 1
      responses:
        '200':
          description: one row in Digital_Two_D_Seismic _Section data is updated
          content:
            application/json:
              example:
                message: The one row in Digital_Two_D_Seismic _Section AFE data is
                  updated
    delete:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Delete Digital_Two_D_Seismic _Section AFE data
      description: Delete Digital_Two_D_Seismic _Section AFE data
      responses:
        '200':
          description: Digital_Two_D_Seismic _Section AFE data is deleted
          content:
            application/json:
              example:
                message: The Digital_Two_D_Seismic _Section AFE data was successfully
                  deleted
  /Digital-Two-D-Seismic -Section-workspace:
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Digital_Two_D_Seismic _Section Workspace
      responses:
        '200':
          description: get Digital_Two_D_Seismic _Section Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                section_id: 1
    post:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Post a new Digital_Two_D_Seismic _Section Workspace
      description: Create a new Digital_Two_D_Seismic _Section Workspace data
      requestBody:
        required: true
        description: Request body to create Digital_Two_D_Seismic _Section Workspace
          data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Two_D_Seismic _Section'
            example:
              Id: 1
              Afe_number: 1
              section_id: 1
      responses:
        '200':
          description: Digital_Two_D_Seismic _Section Workspace data is added
          content:
            application/json:
              example:
                message: The Digital_Two_D_Seismic _Section Workspace data was successfully
                  added
  /Digital-Two-D-Seismic -Section-workspace/{afe}}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Digital_Two_D_Seismic _Section data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Digital_Two_D_Seismic _Section Workspace
      responses:
        '200':
          description: get Digital_Two_D_Seismic _Section Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                section_id: 1
  /Digital-Two-D-Seismic -Section-workspace/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Digital_Two_D_Seismic _Section data to fetch
      schema:
        type: interger
    put:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Digital_Two_D_Seismic _Section Workspace data
      description: Update a new Digital_Two_D_Seismic _Section Workspace Workspace
        data
      requestBody:
        required: true
        description: Request body to update Digital_Two_D_Seismic _Section data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Two_D_Seismic _Section'
            example:
              Id: 1
              Afe_number: 1
              section_id: 1
      responses:
        '200':
          description: Digital_Two_D_Seismic _Section Workspace data is completely
            updated
          content:
            application/json:
              example:
                message: The Digital_Two_D_Seismic _Section Workspace data is completely
                  updated
    patch:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Digital_Two_D_Seismic _Section data
      description: Update a new Digital_Two_D_Seismic _Section data
      requestBody:
        required: true
        description: Request body to update Digital_Two_D_Seismic _Section data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Two_D_Seismic _Section'
            example:
              Id: 1
              Afe_number: 1
              section_id: 1
      responses:
        '200':
          description: one row in Digital_Two_D_Seismic _Section data is updated
          content:
            application/json:
              example:
                message: The one row in Digital_Two_D_Seismic _Section Workspace data
                  is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Delete Digital_Two_D_Seismic _Section Workspace data
      description: Delete Digital_Two_D_Seismic _Section data
      responses:
        '200':
          description: Digital_Two_D_Seismic _Section Workspace data is deleted
          content:
            application/json:
              example:
                message: The Digital_Two_D_Seismic _Section Workspace data was successfully
                  deleted
  /Digital-Two-D-Seismic -Section:
    get:
      security:
      - Authorization: []
      tags:
      - Digital Two D Seismic  Section
      summary: Get Digital_Two_D_Seismic _Section
      responses:
        '200':
          description: get Digital_Two_D_Seismic _Section data to be returned
          content:
            application/json:
              example:
                Ba_long_name: LoremIpsum
                Ba_type: LoremIpsum
                Area_id: LoremIpsum
                Area_type: LoremIpsum
                Acqtn_survey_name: LoremIpsum
                Processing_company: LoremIpsum
                Start_date: LoremIpsum
                Line_name: LoremIpsum
                First_seis_point_id: LoremIpsum
                Last_seis_point_id: LoremIpsum
                Create_date: LoremIpsum
                Proc_set_type: LoremIpsum
                Digital_format: LoremIpsum
                Media_type: LoremIpsum
                Vertical_scale: LoremIpsum
                Vertical_scale_ouom: LoremIpsum
                Horizontal_scale: LoremIpsum
                Horizontal_scale_ouom: LoremIpsum
                Polarity: LoremIpsum
                Data_store_name: LoremIpsum
                Original_file_name: LoremIpsum
                Password: LoremIpsum
                Sw_application_id: LoremIpsum
                Application_version: LoremIpsum
                Digital_size: LoremIpsum
                Digital_size_uom: LoremIpsum
                Remark: LoremIpsum
                Source: LoremIpsum
                Qc_status: LoremIpsum
                Checked_by_ba_id: LoremIpsum
    post:
      security:
      - Authorization: []
      tags:
      - Digital Two D Seismic  Section
      summary: Post a new Digital_Two_D_Seismic _Section
      description: Create a new Digital_Two_D_Seismic _Section data
      requestBody:
        required: true
        description: Request body to create Digital_Two_D_Seismic _Section data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Two_D_Seismic _Section'
            example: []
      responses:
        '200':
          description: Digital_Two_D_Seismic _Section data is added
          content:
            application/json:
              example:
                message: The Digital_Two_D_Seismic _Section data was successfully
                  added
  /Digital-Two-D-Seismic -Section/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Digital_Two_D_Seismic _Section data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Digital Two D Seismic  Section
      summary: Get Digital_Two_D_Seismic _Section
      responses:
        '200':
          description: get Digital_Two_D_Seismic _Section data to be returned
          content:
            application/json:
              example:
              - []
    put:
      security:
      - Authorization: []
      tags:
      - Digital Two D Seismic  Section
      summary: Update a new Digital_Two_D_Seismic _Section data
      description: Update a new Digital_Two_D_Seismic _Section data
      requestBody:
        required: true
        description: Request body to update Digital_Two_D_Seismic _Section data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Two_D_Seismic _Section'
            example: []
      responses:
        '200':
          description: Digital_Two_D_Seismic _Section data is completely updated
          content:
            application/json:
              example:
                message: The Digital_Two_D_Seismic _Section data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Digital Two D Seismic  Section
      summary: Update a new Digital_Two_D_Seismic _Section data
      description: Update a new Digital_Two_D_Seismic _Section data
      requestBody:
        required: true
        description: Request body to update Digital_Two_D_Seismic _Section data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Two_D_Seismic _Section'
            example: []
      responses:
        '200':
          description: one row in Digital_Two_D_Seismic _Section data is updated
          content:
            application/json:
              example:
                message: The one row in Digital_Two_D_Seismic _Section data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Digital Two D Seismic  Section
      summary: Delete Digital_Two_D_Seismic _Section data
      description: Delete Digital_Two_D_Seismic _Section data
      responses:
        '200':
          description: Digital_Two_D_Seismic _Section data is deleted
          content:
            application/json:
              example:
                message: The Digital_Two_D_Seismic _Section data was successfully
                  deleted
  /Digital-Two-D-Seismic -Section/{num}:
    parameters:
    - in: path
      name: num
      required: true
      description: number of dummy data to add
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Digital Two D Seismic  Section Dummy Data
      summary: Add dummy data to Digital_Two_D_Seismic _Section
      responses:
        '200':
          description: add data to Digital_Two_D_Seismic _Section
          content:
            application/json: {}
components:
  schemas:
    afe:
      type: array
      items:
        type: object
        properties:
          afe_number:
            type: integer
          workspace_name:
            type: string
          kkks_name:
            type: string
          working_area:
            type: string
          submission_type:
            type: string
          data_type:
            type: string
    Digital_Two_D_Seismic _Section_workspace:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          afe_number:
            type: integer
          section_id:
            type: integer
    Digital_Two_D_Seismic _Section:
      type: object
      properties:
        Ba_long_name:
          type: string
        Ba_type:
          type: string
        Area_id:
          type: string
        Area_type:
          type: string
        Acqtn_survey_name:
          type: string
        Processing_company:
          type: string
        Start_date:
          type: string
        Line_name:
          type: string
        First_seis_point_id:
          type: string
        Last_seis_point_id:
          type: string
        Create_date:
          type: string
        Proc_set_type:
          type: string
        Digital_format:
          type: string
        Media_type:
          type: string
        Vertical_scale:
          type: string
        Vertical_scale_ouom:
          type: string
        Horizontal_scale:
          type: string
        Horizontal_scale_ouom:
          type: string
        Polarity:
          type: string
        Data_store_name:
          type: string
        Original_file_name:
          type: string
        Password:
          type: string
        Sw_application_id:
          type: string
        Application_version:
          type: string
        Digital_size:
          type: string
        Digital_size_uom:
          type: string
        Remark:
          type: string
        Source:
          type: string
        Qc_status:
          type: string
        Checked_by_ba_id:
          type: string
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: v1/token
