openapi: 3.0.0
info:
  description: This is the swagger API for Non_seismic_and_seismic_non_conventional_digital_data
  version: 1.0.0
  title: Non_seismic_and_seismic_non_conventional_digital_data
  termsOfService: http://swagger.io/terms/
  contact:
    email: darren.mannuela@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- description: Non_seismic_and_seismic_non_conventional_digital_data
  url: http://localhost:8080/api/v1
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/DarrenMannuela/Non_seismic_and_seismic_non_conventional_digital_data/1.0.0
tags:
- name: Afe
  description: All endpoints related to get Non_seismic_and_seismic_non_conventional_digital_data
    AFE
- name: Workspace
  description: All endpoints related to Non_seismic_and_seismic_non_conventional_digital_data
    Workspace
- name: Non_seismic_and_seismic_non_conventional_digital_data
  description: All endpoints related to Non_seismic_and_seismic_non_conventional_digital_data
- name: Non_seismic_and_seismic_non_conventional_digital_data Dummy Data
  description: All endpoints related to Non_seismic_and_seismic_non_conventional_digital_data
- name: User Mgmt
  description: All endpoints related to tokens
paths:
  /Non_seismic_and_seismic_non_conventional_digital_data-afe:
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Non_seismic_and_seismic_non_conventional_digital_data AFE
      responses:
        '200':
          description: get Non_seismic_and_seismic_non_conventional_digital_data AFE
            data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Non_seismic_and_seismic_non_conventional_digital_data
                email: john.richardson@gtn.id
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Afe
      summary: Post a new Non_seismic_and_seismic_non_conventional_digital_data AFE
      description: Create a new Non_seismic_and_seismic_non_conventional_digital_data
        AFE data
      requestBody:
        required: true
        description: Request body to create Non_seismic_and_seismic_non_conventional_digital_data
          AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Non_seismic_and_seismic_non_conventional_digital_data'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Non_seismic_and_seismic_non_conventional_digital_data
              email: john.richardson@gtn.id
      responses:
        '200':
          description: Non_seismic_and_seismic_non_conventional_digital_data data
            is added
          content:
            application/json:
              example:
                message: The Non_seismic_and_seismic_non_conventional_digital_data
                  AFE data was successfully added
  /Non_seismic_and_seismic_non_conventional_digital_data-afe/{afe}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Non_seismic_and_seismic_non_conventional_digital_data data
        to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Non_seismic_and_seismic_non_conventional_digital_data AFE
      responses:
        '200':
          description: get Non_seismic_and_seismic_non_conventional_digital_data AFE
            data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Non_seismic_and_seismic_non_conventional_digital_data
                email: john.richardson@gtn.id
    put:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Non_seismic_and_seismic_non_conventional_digital_data
        AFE data
      description: Update a new Non_seismic_and_seismic_non_conventional_digital_data
        data
      requestBody:
        required: true
        description: Request body to update Non_seismic_and_seismic_non_conventional_digital_data
          AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Non_seismic_and_seismic_non_conventional_digital_data'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Non_seismic_and_seismic_non_conventional_digital_data
              email: john.richardson@gtn.id
      responses:
        '200':
          description: Non_seismic_and_seismic_non_conventional_digital_data data
            is completely updated
          content:
            application/json:
              example:
                message: The Non_seismic_and_seismic_non_conventional_digital_data
                  AFE data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Non_seismic_and_seismic_non_conventional_digital_data
        AFE data
      description: Update a new Non_seismic_and_seismic_non_conventional_digital_data
        data
      requestBody:
        required: true
        description: Request body to update Non_seismic_and_seismic_non_conventional_digital_data
          AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Non_seismic_and_seismic_non_conventional_digital_data'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Non_seismic_and_seismic_non_conventional_digital_data
              email: john.richardson@gtn.id
      responses:
        '200':
          description: one row in Non_seismic_and_seismic_non_conventional_digital_data
            data is updated
          content:
            application/json:
              example:
                message: The one row in Non_seismic_and_seismic_non_conventional_digital_data
                  AFE data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Delete Non_seismic_and_seismic_non_conventional_digital_data AFE data
      description: Delete Non_seismic_and_seismic_non_conventional_digital_data AFE
        data
      responses:
        '200':
          description: Non_seismic_and_seismic_non_conventional_digital_data AFE data
            is deleted
          content:
            application/json:
              example:
                message: The Non_seismic_and_seismic_non_conventional_digital_data
                  AFE data was successfully deleted
  /Non_seismic_and_seismic_non_conventional_digital_data-workspace:
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Non_seismic_and_seismic_non_conventional_digital_data Workspace
      responses:
        '200':
          description: get Non_seismic_and_seismic_non_conventional_digital_data Workspace
            data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Non_seismic_and_seismic_non_conventional_digital_data_id: 1
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Workspace
      summary: Post a new Non_seismic_and_seismic_non_conventional_digital_data Workspace
      description: Create a new Non_seismic_and_seismic_non_conventional_digital_data
        Workspace data
      requestBody:
        required: true
        description: Request body to create Non_seismic_and_seismic_non_conventional_digital_data
          Workspace data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Non_seismic_and_seismic_non_conventional_digital_data'
            example:
              Id: 1
              Afe_number: 1
              Non_seismic_and_seismic_non_conventional_digital_data_id: 1
      responses:
        '200':
          description: Non_seismic_and_seismic_non_conventional_digital_data Workspace
            data is added
          content:
            application/json:
              example:
                message: The Non_seismic_and_seismic_non_conventional_digital_data
                  Workspace data was successfully added
  /Non_seismic_and_seismic_non_conventional_digital_data-workspace/{afe}}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Non_seismic_and_seismic_non_conventional_digital_data data
        to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Non_seismic_and_seismic_non_conventional_digital_data Workspace
      responses:
        '200':
          description: get Non_seismic_and_seismic_non_conventional_digital_data Workspace
            data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Non_seismic_and_seismic_non_conventional_digital_data_id: 1
  /Non_seismic_and_seismic_non_conventional_digital_data-workspace/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Non_seismic_and_seismic_non_conventional_digital_data data
        to fetch
      schema:
        type: integer
    put:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Non_seismic_and_seismic_non_conventional_digital_data
        Workspace data
      description: Update a new Non_seismic_and_seismic_non_conventional_digital_data
        Workspace Workspace data
      requestBody:
        required: true
        description: Request body to update Non_seismic_and_seismic_non_conventional_digital_data
          data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Non_seismic_and_seismic_non_conventional_digital_data'
            example:
              Id: 1
              Afe_number: 1
              Non_seismic_and_seismic_non_conventional_digital_data_id: 1
      responses:
        '200':
          description: Non_seismic_and_seismic_non_conventional_digital_data Workspace
            data is completely updated
          content:
            application/json:
              example:
                message: The Non_seismic_and_seismic_non_conventional_digital_data
                  Workspace data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Non_seismic_and_seismic_non_conventional_digital_data
        data
      description: Update a new Non_seismic_and_seismic_non_conventional_digital_data
        data
      requestBody:
        required: true
        description: Request body to update Non_seismic_and_seismic_non_conventional_digital_data
          data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Non_seismic_and_seismic_non_conventional_digital_data'
            example:
              Id: 1
              Afe_number: 1
              Non_seismic_and_seismic_non_conventional_digital_data_id: 1
      responses:
        '200':
          description: one row in Non_seismic_and_seismic_non_conventional_digital_data
            data is updated
          content:
            application/json:
              example:
                message: The one row in Non_seismic_and_seismic_non_conventional_digital_data
                  Workspace data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Delete Non_seismic_and_seismic_non_conventional_digital_data Workspace
        data
      description: Delete Non_seismic_and_seismic_non_conventional_digital_data data
      responses:
        '200':
          description: Non_seismic_and_seismic_non_conventional_digital_data Workspace
            data is deleted
          content:
            application/json:
              example:
                message: The Non_seismic_and_seismic_non_conventional_digital_data
                  Workspace data was successfully deleted
  /Non_seismic_and_seismic_non_conventional_digital_data:
    get:
      security:
      - Authorization: []
      tags:
      - Non_seismic_and_seismic_non_conventional_digital_data
      summary: Get Non_seismic_and_seismic_non_conventional_digital_data
      responses:
        '200':
          description: get Non_seismic_and_seismic_non_conventional_digital_data data
            to be returned
          content:
            application/json:
              example:
                Id: 1
                Ba_long_name: LoremIpsum
                Ba_type: LoremIpsum
                Area_id: LoremIpsum
                Area_type: LoremIpsum
                Acqtn_survey_name: LoremIpsum
                Processing_company: LoremIpsum
                Start_date: LoremIpsum
                Seis_station_type: LoremIpsum
                Create_date: LoremIpsum
                Proc_set_type: LoremIpsum
                Media_type: LoremIpsum
                Tape_number: LoremIpsum
                Digital_format: LoremIpsum
                Ba_long_name_2: LoremIpsum
                Ba_type_2: LoremIpsum
                Data_store_name: LoremIpsum
                Original_file_name: LoremIpsum
                Password_: LoremIpsum
                Digital_size: 1
                Digital_size_uom: LoremIpsum
                Remark_: LoremIpsum
                Source_: LoremIpsum
                Qc_status: LoremIpsum
                Checked_by_ba_id: LoremIpsum
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Non_seismic_and_seismic_non_conventional_digital_data
      summary: Post a new Non_seismic_and_seismic_non_conventional_digital_data
      description: Create a new Non_seismic_and_seismic_non_conventional_digital_data
        data
      requestBody:
        required: true
        description: Request body to create Non_seismic_and_seismic_non_conventional_digital_data
          data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Non_seismic_and_seismic_non_conventional_digital_data'
            example: []
      responses:
        '200':
          description: Non_seismic_and_seismic_non_conventional_digital_data data
            is added
          content:
            application/json:
              example:
                message: The Non_seismic_and_seismic_non_conventional_digital_data
                  data was successfully added
  /Non_seismic_and_seismic_non_conventional_digital_data/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Non_seismic_and_seismic_non_conventional_digital_data data
        to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Non_seismic_and_seismic_non_conventional_digital_data
      summary: Get Non_seismic_and_seismic_non_conventional_digital_data
      responses:
        '200':
          description: get Non_seismic_and_seismic_non_conventional_digital_data data
            to be returned
          content:
            application/json:
              example:
              - []
    put:
      security:
      - Authorization: []
      tags:
      - Non_seismic_and_seismic_non_conventional_digital_data
      summary: Update a new Non_seismic_and_seismic_non_conventional_digital_data
        data
      description: Update a new Non_seismic_and_seismic_non_conventional_digital_data
        data
      requestBody:
        required: true
        description: Request body to update Non_seismic_and_seismic_non_conventional_digital_data
          data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Non_seismic_and_seismic_non_conventional_digital_data'
            example: []
      responses:
        '200':
          description: Non_seismic_and_seismic_non_conventional_digital_data data
            is completely updated
          content:
            application/json:
              example:
                message: The Non_seismic_and_seismic_non_conventional_digital_data
                  data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Non_seismic_and_seismic_non_conventional_digital_data
      summary: Update a new Non_seismic_and_seismic_non_conventional_digital_data
        data
      description: Update a new Non_seismic_and_seismic_non_conventional_digital_data
        data
      requestBody:
        required: true
        description: Request body to update Non_seismic_and_seismic_non_conventional_digital_data
          data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Non_seismic_and_seismic_non_conventional_digital_data'
            example: []
      responses:
        '200':
          description: one row in Non_seismic_and_seismic_non_conventional_digital_data
            data is updated
          content:
            application/json:
              example:
                message: The one row in Non_seismic_and_seismic_non_conventional_digital_data
                  data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Non_seismic_and_seismic_non_conventional_digital_data
      summary: Delete Non_seismic_and_seismic_non_conventional_digital_data data
      description: Delete Non_seismic_and_seismic_non_conventional_digital_data data
      responses:
        '200':
          description: Non_seismic_and_seismic_non_conventional_digital_data data
            is deleted
          content:
            application/json:
              example:
                message: The Non_seismic_and_seismic_non_conventional_digital_data
                  data was successfully deleted
  /Non_seismic_and_seismic_non_conventional_digital_data/{num}:
    parameters:
    - in: path
      name: num
      required: true
      description: number of dummy data to add
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Non_seismic_and_seismic_non_conventional_digital_data Dummy Data
      summary: Add dummy data to Non_seismic_and_seismic_non_conventional_digital_data
      responses:
        '200':
          description: add data to Non_seismic_and_seismic_non_conventional_digital_data
          content:
            application/json: {}
  /token:
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - User Mgmt
      summary: Login For Access Token
      operationId: login_for_access_token_token_post
      requestBody:
        required: true
        description: Request body to create Non_seismic_and_seismic_non_conventional_digital_data
          AFE data
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Body_login_for_access_token_token_post'
            example: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    afe:
      type: array
      items:
        type: object
        properties:
          afe_number:
            type: integer
          workspace_name:
            type: string
          kkks_name:
            type: string
          working_area:
            type: string
          submission_type:
            type: string
          data_type:
            type: string
    Token:
      title: Token
      required:
      - access_token
      - token_type
      - type
      - name
      - expiry_date
      - affiliation
      type: object
      properties:
        access_token:
          title: Access Token
          type: string
        token_type:
          title: Token Type
          type: string
        type:
          $ref: '#/components/schemas/UserType'
        name:
          title: Name
          type: string
        expiry_date:
          title: Expiry Date
          type: string
        affiliation:
          title: Affiliation
          type: string
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    UserType:
      title: UserType
      enum:
      - Administrator
      - Regular User
      - Premium User
      type: string
      description: An enumeration.
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    Body_login_for_access_token_token_post:
      title: Body_login_for_access_token_token_post
      required:
      - username
      - password
      type: object
      properties:
        grant_type:
          title: Grant Type
          pattern: password
          type: string
        username:
          title: Username
          type: string
        password:
          title: Password
          type: string
        scope:
          title: Scope
          type: string
          default: ''
        client_id:
          title: Client Id
          type: string
        client_secret:
          title: Client Secret
          type: string
    Non_seismic_and_seismic_non_conventional_digital_data_workspace:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          afe_number:
            type: integer
          Non_seismic_and_seismic_non_conventional_digital_data_id:
            type: integer
    Non_seismic_and_seismic_non_conventional_digital_data:
      type: object
      properties:
        Id:
          type: integer
        Ba_long_name:
          type: string
        Ba_type:
          type: string
        Area_id:
          type: string
        Area_type:
          type: string
        Acqtn_survey_name:
          type: string
        Processing_company:
          type: string
        Start_date:
          type: string
        Seis_station_type:
          type: string
        Create_date:
          type: string
        Proc_set_type:
          type: string
        Media_type:
          type: string
        Tape_number:
          type: string
        Digital_format:
          type: string
        Ba_long_name_2:
          type: string
        Ba_type_2:
          type: string
        Data_store_name:
          type: string
        Original_file_name:
          type: string
        Password_:
          type: string
        Digital_size:
          type: integer
        Digital_size_uom:
          type: string
        Remark_:
          type: string
        Source_:
          type: string
        Qc_status:
          type: string
        Checked_by_ba_id:
          type: string
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: v1/token
