openapi: 3.0.0
info:
  description: This is the swagger API for Print_Well_Report
  version: 1.0.0
  title: Print_Well_Report
  termsOfService: http://swagger.io/terms/
  contact:
    email: darren.mannuela@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- description: Print_Well_Report
  url: http://localhost:8080/api/v1
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/DarrenMannuela/Print_Well_Report/1.0.0
tags:
- name: Afe
  description: All endpoints related to get Print_Well_Report AFE
- name: Workspace
  description: All endpoints related to Print_Well_Report Workspace
- name: Print Well Report
  description: All endpoints related to Print_Well_Report
- name: Print Well Report Dummy Data
  description: All endpoints related to Print_Well_Report
paths:
  /Print-Well-Report-afe:
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Print_Well_Report AFE
      responses:
        '200':
          description: get Print_Well_Report AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Print Well Report
              user_id: 1
    post:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Post a new Print_Well_Report AFE
      description: Create a new Print_Well_Report AFE data
      requestBody:
        required: true
        description: Request body to create Print_Well_Report AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Print_Well_Report'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Print Well Report
            user_id: 1
      responses:
        '200':
          description: Print_Well_Report data is added
          content:
            application/json:
              example:
                message: The Print_Well_Report AFE data was successfully added
  /Print-Well-Report-afe/{afe}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Print_Well_Report data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Print_Well_Report AFE
      responses:
        '200':
          description: get Print_Well_Report AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Print Well Report
              user_id: 1
    put:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Print_Well_Report AFE data
      description: Update a new Print_Well_Report data
      requestBody:
        required: true
        description: Request body to update Print_Well_Report AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Print_Well_Report'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Print Well Report
            user_id: 1
      responses:
        '200':
          description: Print_Well_Report data is completely updated
          content:
            application/json:
              example:
                message: The Print_Well_Report AFE data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Print_Well_Report AFE data
      description: Update a new Print_Well_Report data
      requestBody:
        required: true
        description: Request body to update Print_Well_Report AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Print_Well_Report'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Print Well Report
            user_id: 1
      responses:
        '200':
          description: one row in Print_Well_Report data is updated
          content:
            application/json:
              example:
                message: The one row in Print_Well_Report AFE data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Delete Print_Well_Report AFE data
      description: Delete Print_Well_Report AFE data
      responses:
        '200':
          description: Print_Well_Report AFE data is deleted
          content:
            application/json:
              example:
                message: The Print_Well_Report AFE data was successfully deleted
  /Print-Well-Report-workspace:
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Print_Well_Report Workspace
      responses:
        '200':
          description: get Print_Well_Report Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Print_well_report_id: 1
    post:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Post a new Print_Well_Report Workspace
      description: Create a new Print_Well_Report Workspace data
      requestBody:
        required: true
        description: Request body to create Print_Well_Report Workspace data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Print_Well_Report'
            example:
              Id: 1
              Afe_number: 1
              Print_well_report_id: 1
      responses:
        '200':
          description: Print_Well_Report Workspace data is added
          content:
            application/json:
              example:
                message: The Print_Well_Report Workspace data was successfully added
  /Print-Well-Report-workspace/{afe}}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Print_Well_Report data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Print_Well_Report Workspace
      responses:
        '200':
          description: get Print_Well_Report Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Print_well_report_id: 1
  /Print-Well-Report-workspace/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Print_Well_Report data to fetch
      schema:
        type: interger
    put:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Print_Well_Report Workspace data
      description: Update a new Print_Well_Report Workspace Workspace data
      requestBody:
        required: true
        description: Request body to update Print_Well_Report data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Print_Well_Report'
            example:
              Id: 1
              Afe_number: 1
              Print_well_report_id: 1
      responses:
        '200':
          description: Print_Well_Report Workspace data is completely updated
          content:
            application/json:
              example:
                message: The Print_Well_Report Workspace data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Print_Well_Report data
      description: Update a new Print_Well_Report data
      requestBody:
        required: true
        description: Request body to update Print_Well_Report data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Print_Well_Report'
            example:
              Id: 1
              Afe_number: 1
              Print_well_report_id: 1
      responses:
        '200':
          description: one row in Print_Well_Report data is updated
          content:
            application/json:
              example:
                message: The one row in Print_Well_Report Workspace data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Delete Print_Well_Report Workspace data
      description: Delete Print_Well_Report data
      responses:
        '200':
          description: Print_Well_Report Workspace data is deleted
          content:
            application/json:
              example:
                message: The Print_Well_Report Workspace data was successfully deleted
  /Print-Well-Report:
    get:
      security:
      - Authorization: []
      tags:
      - Print Well Report
      summary: Get Print_Well_Report
      responses:
        '200':
          description: get Print_Well_Report data to be returned
          content:
            application/json:
              example:
                Ba_long_name: LoremIpsum
                Ba_type: LoremIpsum
                Area_id: LoremIpsum
                Area_type: LoremIpsum
                Field_name: LoremIpsum
                Well_name: LoremIpsum
                Uwi: LoremIpsum
                Title: LoremIpsum
                Creator_name: LoremIpsum
                Create_date: LoremIpsum
                Media_type: LoremIpsum
                Document_type: LoremIpsum
                Item_category: LoremIpsum
                Item_sub_category: LoremIpsum
                Page_count: LoremIpsum
                Remark: LoremIpsum
                Data_store_name: LoremIpsum
                Data_store_type: LoremIpsum
                Source: LoremIpsum
                Qc_status: LoremIpsum
                Checked_by_ba_id: LoremIpsum
    post:
      security:
      - Authorization: []
      tags:
      - Print Well Report
      summary: Post a new Print_Well_Report
      description: Create a new Print_Well_Report data
      requestBody:
        required: true
        description: Request body to create Print_Well_Report data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Print_Well_Report'
            example: []
      responses:
        '200':
          description: Print_Well_Report data is added
          content:
            application/json:
              example:
                message: The Print_Well_Report data was successfully added
  /Print-Well-Report/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Print_Well_Report data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Print Well Report
      summary: Get Print_Well_Report
      responses:
        '200':
          description: get Print_Well_Report data to be returned
          content:
            application/json:
              example:
              - []
    put:
      security:
      - Authorization: []
      tags:
      - Print Well Report
      summary: Update a new Print_Well_Report data
      description: Update a new Print_Well_Report data
      requestBody:
        required: true
        description: Request body to update Print_Well_Report data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Print_Well_Report'
            example: []
      responses:
        '200':
          description: Print_Well_Report data is completely updated
          content:
            application/json:
              example:
                message: The Print_Well_Report data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Print Well Report
      summary: Update a new Print_Well_Report data
      description: Update a new Print_Well_Report data
      requestBody:
        required: true
        description: Request body to update Print_Well_Report data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Print_Well_Report'
            example: []
      responses:
        '200':
          description: one row in Print_Well_Report data is updated
          content:
            application/json:
              example:
                message: The one row in Print_Well_Report data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Print Well Report
      summary: Delete Print_Well_Report data
      description: Delete Print_Well_Report data
      responses:
        '200':
          description: Print_Well_Report data is deleted
          content:
            application/json:
              example:
                message: The Print_Well_Report data was successfully deleted
  /Print-Well-Report/{num}:
    parameters:
    - in: path
      name: num
      required: true
      description: number of dummy data to add
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Print Well Report Dummy Data
      summary: Add dummy data to Print_Well_Report
      responses:
        '200':
          description: add data to Print_Well_Report
          content:
            application/json: {}
components:
  schemas:
    afe:
      type: array
      items:
        type: object
        properties:
          afe_number:
            type: integer
          workspace_name:
            type: string
          kkks_name:
            type: string
          working_area:
            type: string
          submission_type:
            type: string
          data_type:
            type: string
    Print_Well_Report_workspace:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          afe_number:
            type: integer
          Print_well_report_id:
            type: integer
    Print_Well_Report:
      type: object
      properties:
        Ba_long_name:
          type: string
        Ba_type:
          type: string
        Area_id:
          type: string
        Area_type:
          type: string
        Field_name:
          type: string
        Well_name:
          type: string
        Uwi:
          type: string
        Title:
          type: string
        Creator_name:
          type: string
        Create_date:
          type: string
        Media_type:
          type: string
        Document_type:
          type: string
        Item_category:
          type: string
        Item_sub_category:
          type: string
        Page_count:
          type: string
        Remark:
          type: string
        Data_store_name:
          type: string
        Data_store_type:
          type: string
        Source:
          type: string
        Qc_status:
          type: string
        Checked_by_ba_id:
          type: string
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: v1/token
