openapi: 3.0.0
info:
  description: This is the swagger API for T3_D_seismic_summary
  version: 1.0.0
  title: T3_D_seismic_summary
  termsOfService: http://swagger.io/terms/
  contact:
    email: darren.mannuela@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- description: T3_D_seismic_summary
  url: http://localhost:8080/api/v1
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/DarrenMannuela/T3_D_seismic_summary/1.0.0
tags:
- name: Afe
  description: All endpoints related to get T3_D_seismic_summary AFE
- name: Workspace
  description: All endpoints related to T3_D_seismic_summary Workspace
- name: T3 D_seismic_summary
  description: All endpoints related to T3_D_seismic_summary
- name: T3 D_seismic_summary Dummy Data
  description: All endpoints related to T3_D_seismic_summary
- name: User Mgmt
  description: All endpoints related to tokens
paths:
  /T3-D_seismic_summary-afe:
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get T3_D_seismic_summary AFE
      responses:
        '200':
          description: get T3_D_seismic_summary AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: T3 D_seismic_summary
                email: john.richardson@gtn.id
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Afe
      summary: Post a new T3_D_seismic_summary AFE
      description: Create a new T3_D_seismic_summary AFE data
      requestBody:
        required: true
        description: Request body to create T3_D_seismic_summary AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/T3_D_seismic_summary'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: T3 D_seismic_summary
              email: john.richardson@gtn.id
      responses:
        '200':
          description: T3_D_seismic_summary data is added
          content:
            application/json:
              example:
                message: The T3_D_seismic_summary AFE data was successfully added
  /T3-D_seismic_summary-afe/{afe}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of T3_D_seismic_summary data to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get T3_D_seismic_summary AFE
      responses:
        '200':
          description: get T3_D_seismic_summary AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: T3 D_seismic_summary
                email: john.richardson@gtn.id
    put:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new T3_D_seismic_summary AFE data
      description: Update a new T3_D_seismic_summary data
      requestBody:
        required: true
        description: Request body to update T3_D_seismic_summary AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/T3_D_seismic_summary'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: T3 D_seismic_summary
              email: john.richardson@gtn.id
      responses:
        '200':
          description: T3_D_seismic_summary data is completely updated
          content:
            application/json:
              example:
                message: The T3_D_seismic_summary AFE data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new T3_D_seismic_summary AFE data
      description: Update a new T3_D_seismic_summary data
      requestBody:
        required: true
        description: Request body to update T3_D_seismic_summary AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/T3_D_seismic_summary'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: T3 D_seismic_summary
              email: john.richardson@gtn.id
      responses:
        '200':
          description: one row in T3_D_seismic_summary data is updated
          content:
            application/json:
              example:
                message: The one row in T3_D_seismic_summary AFE data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Delete T3_D_seismic_summary AFE data
      description: Delete T3_D_seismic_summary AFE data
      responses:
        '200':
          description: T3_D_seismic_summary AFE data is deleted
          content:
            application/json:
              example:
                message: The T3_D_seismic_summary AFE data was successfully deleted
  /T3-D_seismic_summary-workspace:
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get T3_D_seismic_summary Workspace
      responses:
        '200':
          description: get T3_D_seismic_summary Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                T3D_seismic_summary_id: 1
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Workspace
      summary: Post a new T3_D_seismic_summary Workspace
      description: Create a new T3_D_seismic_summary Workspace data
      requestBody:
        required: true
        description: Request body to create T3_D_seismic_summary Workspace data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/T3_D_seismic_summary'
            example:
              Id: 1
              Afe_number: 1
              T3D_seismic_summary_id: 1
      responses:
        '200':
          description: T3_D_seismic_summary Workspace data is added
          content:
            application/json:
              example:
                message: The T3_D_seismic_summary Workspace data was successfully
                  added
  /T3-D_seismic_summary-workspace/{afe}}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of T3_D_seismic_summary data to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get T3_D_seismic_summary Workspace
      responses:
        '200':
          description: get T3_D_seismic_summary Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                T3D_seismic_summary_id: 1
  /T3-D_seismic_summary-workspace/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of T3_D_seismic_summary data to fetch
      schema:
        type: integer
    put:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new T3_D_seismic_summary Workspace data
      description: Update a new T3_D_seismic_summary Workspace Workspace data
      requestBody:
        required: true
        description: Request body to update T3_D_seismic_summary data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/T3_D_seismic_summary'
            example:
              Id: 1
              Afe_number: 1
              T3D_seismic_summary_id: 1
      responses:
        '200':
          description: T3_D_seismic_summary Workspace data is completely updated
          content:
            application/json:
              example:
                message: The T3_D_seismic_summary Workspace data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new T3_D_seismic_summary data
      description: Update a new T3_D_seismic_summary data
      requestBody:
        required: true
        description: Request body to update T3_D_seismic_summary data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/T3_D_seismic_summary'
            example:
              Id: 1
              Afe_number: 1
              T3D_seismic_summary_id: 1
      responses:
        '200':
          description: one row in T3_D_seismic_summary data is updated
          content:
            application/json:
              example:
                message: The one row in T3_D_seismic_summary Workspace data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Delete T3_D_seismic_summary Workspace data
      description: Delete T3_D_seismic_summary data
      responses:
        '200':
          description: T3_D_seismic_summary Workspace data is deleted
          content:
            application/json:
              example:
                message: The T3_D_seismic_summary Workspace data was successfully
                  deleted
  /T3-D_seismic_summary:
    get:
      security:
      - Authorization: []
      tags:
      - T3 D_seismic_summary
      summary: Get T3_D_seismic_summary
      responses:
        '200':
          description: get T3_D_seismic_summary data to be returned
          content:
            application/json:
              example:
                Id: 1
                Ba_long_name: LoremIpsum
                Ba_type: LoremIpsum
                Area_id: LoremIpsum
                Area_type: LoremIpsum
                Acqtn_survey_name: LoremIpsum
                Area_size: 1
                Area_size_ouom: LoremIpsum
                Acqtn_inline_bin_size: 1
                Acqtn_inline_bin_size_ouom: LoremIpsum
                Acqtn_xline_bin_size: 1
                Acqtn_xline_bin_size_ouom: LoremIpsum
                Seis_dimension: LoremIpsum
                Start_date: LoremIpsum
                Shot_by: LoremIpsum
                Crew_long_name: LoremIpsum
                Acqtn_shot_line_spacing: 1
                Acqtn_shot_line_spacing_ouom: LoremIpsum
                Rcvr_spacing: 1
                Rcvr_spacing_ouom: LoremIpsum
                Rcvr_line_spacing: 1
                Rcvr_line_spacing_ouom: LoremIpsum
                Seis_3d_type: LoremIpsum
                Energy_type: LoremIpsum
                Fold_coverage: 1
                Rcrd_channel_count: 1
                Rcrd_rec_length: 1
                Rcrd_rec_length_ouom: LoremIpsum
                Rcrd_sample_rate: 1
                Rcrd_sample_rate_ouom: LoremIpsum
                Alias_long_name: LoremIpsum
                Environment_: LoremIpsum
                Remark_: LoremIpsum
                Source_: LoremIpsum
                Qc_status: LoremIpsum
                Checked_by_ba_id: LoremIpsum
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - T3 D_seismic_summary
      summary: Post a new T3_D_seismic_summary
      description: Create a new T3_D_seismic_summary data
      requestBody:
        required: true
        description: Request body to create T3_D_seismic_summary data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/T3_D_seismic_summary'
            example: []
      responses:
        '200':
          description: T3_D_seismic_summary data is added
          content:
            application/json:
              example:
                message: The T3_D_seismic_summary data was successfully added
  /T3-D_seismic_summary/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of T3_D_seismic_summary data to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - T3 D_seismic_summary
      summary: Get T3_D_seismic_summary
      responses:
        '200':
          description: get T3_D_seismic_summary data to be returned
          content:
            application/json:
              example:
              - []
    put:
      security:
      - Authorization: []
      tags:
      - T3 D_seismic_summary
      summary: Update a new T3_D_seismic_summary data
      description: Update a new T3_D_seismic_summary data
      requestBody:
        required: true
        description: Request body to update T3_D_seismic_summary data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/T3_D_seismic_summary'
            example: []
      responses:
        '200':
          description: T3_D_seismic_summary data is completely updated
          content:
            application/json:
              example:
                message: The T3_D_seismic_summary data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - T3 D_seismic_summary
      summary: Update a new T3_D_seismic_summary data
      description: Update a new T3_D_seismic_summary data
      requestBody:
        required: true
        description: Request body to update T3_D_seismic_summary data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/T3_D_seismic_summary'
            example: []
      responses:
        '200':
          description: one row in T3_D_seismic_summary data is updated
          content:
            application/json:
              example:
                message: The one row in T3_D_seismic_summary data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - T3 D_seismic_summary
      summary: Delete T3_D_seismic_summary data
      description: Delete T3_D_seismic_summary data
      responses:
        '200':
          description: T3_D_seismic_summary data is deleted
          content:
            application/json:
              example:
                message: The T3_D_seismic_summary data was successfully deleted
  /T3-D_seismic_summary/{num}:
    parameters:
    - in: path
      name: num
      required: true
      description: number of dummy data to add
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - T3 D_seismic_summary Dummy Data
      summary: Add dummy data to T3_D_seismic_summary
      responses:
        '200':
          description: add data to T3_D_seismic_summary
          content:
            application/json: {}
  /token:
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - User Mgmt
      summary: Login For Access Token
      operationId: login_for_access_token_token_post
      requestBody:
        required: true
        description: Request body to create T3_D_seismic_summary AFE data
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Body_login_for_access_token_token_post'
            example: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    afe:
      type: array
      items:
        type: object
        properties:
          afe_number:
            type: integer
          workspace_name:
            type: string
          kkks_name:
            type: string
          working_area:
            type: string
          submission_type:
            type: string
          data_type:
            type: string
    Token:
      title: Token
      required:
      - access_token
      - token_type
      - type
      - name
      - expiry_date
      - affiliation
      type: object
      properties:
        access_token:
          title: Access Token
          type: string
        token_type:
          title: Token Type
          type: string
        type:
          $ref: '#/components/schemas/UserType'
        name:
          title: Name
          type: string
        expiry_date:
          title: Expiry Date
          type: string
        affiliation:
          title: Affiliation
          type: string
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    UserType:
      title: UserType
      enum:
      - Administrator
      - Regular User
      - Premium User
      type: string
      description: An enumeration.
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    Body_login_for_access_token_token_post:
      title: Body_login_for_access_token_token_post
      required:
      - username
      - password
      type: object
      properties:
        grant_type:
          title: Grant Type
          pattern: password
          type: string
        username:
          title: Username
          type: string
        password:
          title: Password
          type: string
        scope:
          title: Scope
          type: string
          default: ''
        client_id:
          title: Client Id
          type: string
        client_secret:
          title: Client Secret
          type: string
    T3_D_seismic_summary_workspace:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          afe_number:
            type: integer
          T3D_seismic_summary_id:
            type: integer
    T3_D_seismic_summary:
      type: object
      properties:
        Id:
          type: integer
        Ba_long_name:
          type: string
        Ba_type:
          type: string
        Area_id:
          type: string
        Area_type:
          type: string
        Acqtn_survey_name:
          type: string
        Area_size:
          type: integer
        Area_size_ouom:
          type: string
        Acqtn_inline_bin_size:
          type: integer
        Acqtn_inline_bin_size_ouom:
          type: string
        Acqtn_xline_bin_size:
          type: integer
        Acqtn_xline_bin_size_ouom:
          type: string
        Seis_dimension:
          type: string
        Start_date:
          type: string
        Shot_by:
          type: string
        Crew_long_name:
          type: string
        Acqtn_shot_line_spacing:
          type: integer
        Acqtn_shot_line_spacing_ouom:
          type: string
        Rcvr_spacing:
          type: integer
        Rcvr_spacing_ouom:
          type: string
        Rcvr_line_spacing:
          type: integer
        Rcvr_line_spacing_ouom:
          type: string
        Seis_3d_type:
          type: string
        Energy_type:
          type: string
        Fold_coverage:
          type: integer
        Rcrd_channel_count:
          type: integer
        Rcrd_rec_length:
          type: integer
        Rcrd_rec_length_ouom:
          type: string
        Rcrd_sample_rate:
          type: integer
        Rcrd_sample_rate_ouom:
          type: string
        Alias_long_name:
          type: string
        Environment_:
          type: string
        Remark_:
          type: string
        Source_:
          type: string
        Qc_status:
          type: string
        Checked_by_ba_id:
          type: string
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: v1/token
