openapi: 3.0.0
info:
  description: This is the swagger API for Three_D_Seismic_Field_Digital_Data
  version: 1.0.0
  title: Three_D_Seismic_Field_Digital_Data
  termsOfService: http://swagger.io/terms/
  contact:
    email: darren.mannuela@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- description: Three_D_Seismic_Field_Digital_Data
  url: http://localhost:8080/api/v1
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/DarrenMannuela/Three_D_Seismic_Field_Digital_Data/1.0.0
tags:
- name: Afe
  description: All endpoints related to get Three_D_Seismic_Field_Digital_Data AFE
- name: Workspace
  description: All endpoints related to Three_D_Seismic_Field_Digital_Data Workspace
- name: Three D Seismic Field Digital Data
  description: All endpoints related to Three_D_Seismic_Field_Digital_Data
- name: Three D Seismic Field Digital Data Dummy Data
  description: All endpoints related to Three_D_Seismic_Field_Digital_Data
- name: User Mgmt
  description: All endpoints related to tokens
paths:
  /Three-D-Seismic-Field-Digital-Data-afe:
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Three_D_Seismic_Field_Digital_Data AFE
      responses:
        '200':
          description: get Three_D_Seismic_Field_Digital_Data AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Three D Seismic Field Digital Data
                email: john.richardson@gtn.id
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Afe
      summary: Post a new Three_D_Seismic_Field_Digital_Data AFE
      description: Create a new Three_D_Seismic_Field_Digital_Data AFE data
      requestBody:
        required: true
        description: Request body to create Three_D_Seismic_Field_Digital_Data AFE
          data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Three_D_Seismic_Field_Digital_Data'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Three D Seismic Field Digital Data
              email: john.richardson@gtn.id
      responses:
        '200':
          description: Three_D_Seismic_Field_Digital_Data data is added
          content:
            application/json:
              example:
                message: The Three_D_Seismic_Field_Digital_Data AFE data was successfully
                  added
  /Three-D-Seismic-Field-Digital-Data-afe/{afe}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Three_D_Seismic_Field_Digital_Data data to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Three_D_Seismic_Field_Digital_Data AFE
      responses:
        '200':
          description: get Three_D_Seismic_Field_Digital_Data AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Three D Seismic Field Digital Data
                email: john.richardson@gtn.id
    put:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Three_D_Seismic_Field_Digital_Data AFE data
      description: Update a new Three_D_Seismic_Field_Digital_Data data
      requestBody:
        required: true
        description: Request body to update Three_D_Seismic_Field_Digital_Data AFE
          data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Three_D_Seismic_Field_Digital_Data'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Three D Seismic Field Digital Data
              email: john.richardson@gtn.id
      responses:
        '200':
          description: Three_D_Seismic_Field_Digital_Data data is completely updated
          content:
            application/json:
              example:
                message: The Three_D_Seismic_Field_Digital_Data AFE data is completely
                  updated
    patch:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Three_D_Seismic_Field_Digital_Data AFE data
      description: Update a new Three_D_Seismic_Field_Digital_Data data
      requestBody:
        required: true
        description: Request body to update Three_D_Seismic_Field_Digital_Data AFE
          data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Three_D_Seismic_Field_Digital_Data'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Three D Seismic Field Digital Data
              email: john.richardson@gtn.id
      responses:
        '200':
          description: one row in Three_D_Seismic_Field_Digital_Data data is updated
          content:
            application/json:
              example:
                message: The one row in Three_D_Seismic_Field_Digital_Data AFE data
                  is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Delete Three_D_Seismic_Field_Digital_Data AFE data
      description: Delete Three_D_Seismic_Field_Digital_Data AFE data
      responses:
        '200':
          description: Three_D_Seismic_Field_Digital_Data AFE data is deleted
          content:
            application/json:
              example:
                message: The Three_D_Seismic_Field_Digital_Data AFE data was successfully
                  deleted
  /Three-D-Seismic-Field-Digital-Data-workspace:
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Three_D_Seismic_Field_Digital_Data Workspace
      responses:
        '200':
          description: get Three_D_Seismic_Field_Digital_Data Workspace data to be
            returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Three_d_seismic_field_digital_data_id: 1
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Workspace
      summary: Post a new Three_D_Seismic_Field_Digital_Data Workspace
      description: Create a new Three_D_Seismic_Field_Digital_Data Workspace data
      requestBody:
        required: true
        description: Request body to create Three_D_Seismic_Field_Digital_Data Workspace
          data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Three_D_Seismic_Field_Digital_Data'
            example:
              Id: 1
              Afe_number: 1
              Three_d_seismic_field_digital_data_id: 1
      responses:
        '200':
          description: Three_D_Seismic_Field_Digital_Data Workspace data is added
          content:
            application/json:
              example:
                message: The Three_D_Seismic_Field_Digital_Data Workspace data was
                  successfully added
  /Three-D-Seismic-Field-Digital-Data-workspace/{afe}}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Three_D_Seismic_Field_Digital_Data data to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Three_D_Seismic_Field_Digital_Data Workspace
      responses:
        '200':
          description: get Three_D_Seismic_Field_Digital_Data Workspace data to be
            returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Three_d_seismic_field_digital_data_id: 1
  /Three-D-Seismic-Field-Digital-Data-workspace/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Three_D_Seismic_Field_Digital_Data data to fetch
      schema:
        type: integer
    put:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Three_D_Seismic_Field_Digital_Data Workspace data
      description: Update a new Three_D_Seismic_Field_Digital_Data Workspace Workspace
        data
      requestBody:
        required: true
        description: Request body to update Three_D_Seismic_Field_Digital_Data data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Three_D_Seismic_Field_Digital_Data'
            example:
              Id: 1
              Afe_number: 1
              Three_d_seismic_field_digital_data_id: 1
      responses:
        '200':
          description: Three_D_Seismic_Field_Digital_Data Workspace data is completely
            updated
          content:
            application/json:
              example:
                message: The Three_D_Seismic_Field_Digital_Data Workspace data is
                  completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Three_D_Seismic_Field_Digital_Data data
      description: Update a new Three_D_Seismic_Field_Digital_Data data
      requestBody:
        required: true
        description: Request body to update Three_D_Seismic_Field_Digital_Data data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Three_D_Seismic_Field_Digital_Data'
            example:
              Id: 1
              Afe_number: 1
              Three_d_seismic_field_digital_data_id: 1
      responses:
        '200':
          description: one row in Three_D_Seismic_Field_Digital_Data data is updated
          content:
            application/json:
              example:
                message: The one row in Three_D_Seismic_Field_Digital_Data Workspace
                  data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Delete Three_D_Seismic_Field_Digital_Data Workspace data
      description: Delete Three_D_Seismic_Field_Digital_Data data
      responses:
        '200':
          description: Three_D_Seismic_Field_Digital_Data Workspace data is deleted
          content:
            application/json:
              example:
                message: The Three_D_Seismic_Field_Digital_Data Workspace data was
                  successfully deleted
  /Three-D-Seismic-Field-Digital-Data:
    get:
      security:
      - Authorization: []
      tags:
      - Three D Seismic Field Digital Data
      summary: Get Three_D_Seismic_Field_Digital_Data
      responses:
        '200':
          description: get Three_D_Seismic_Field_Digital_Data data to be returned
          content:
            application/json:
              example:
                Ba_long_name: LoremIpsum
                Ba_type: LoremIpsum
                Area_id: LoremIpsum
                Area_type: LoremIpsum
                Acqtn_survey_name: LoremIpsum
                Start_date: LoremIpsum
                Shot_by: LoremIpsum
                Rcrd_rec_length: LoremIpsum
                Rcrd_rec_length_ouom: LoremIpsum
                Rcrd_sample_rate: LoremIpsum
                Rcrd_sample_rate_ouom: LoremIpsum
                First_seis_point_id: LoremIpsum
                Last_seis_point_id: LoremIpsum
                Create_date: LoremIpsum
                Proc_set_type: LoremIpsum
                Field_file_number: LoremIpsum
                Tape_number: LoremIpsum
                Rcrd_format_type: LoremIpsum
                Data_store_name: LoremIpsum
                Original_file_name: LoremIpsum
                Password: LoremIpsum
                Digital_size: LoremIpsum
                Digital_size_uom: LoremIpsum
                Remark: LoremIpsum
                Source: LoremIpsum
                Qc_status: LoremIpsum
                Checked_by_ba_id: LoremIpsum
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Three D Seismic Field Digital Data
      summary: Post a new Three_D_Seismic_Field_Digital_Data
      description: Create a new Three_D_Seismic_Field_Digital_Data data
      requestBody:
        required: true
        description: Request body to create Three_D_Seismic_Field_Digital_Data data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Three_D_Seismic_Field_Digital_Data'
            example: []
      responses:
        '200':
          description: Three_D_Seismic_Field_Digital_Data data is added
          content:
            application/json:
              example:
                message: The Three_D_Seismic_Field_Digital_Data data was successfully
                  added
  /Three-D-Seismic-Field-Digital-Data/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Three_D_Seismic_Field_Digital_Data data to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Three D Seismic Field Digital Data
      summary: Get Three_D_Seismic_Field_Digital_Data
      responses:
        '200':
          description: get Three_D_Seismic_Field_Digital_Data data to be returned
          content:
            application/json:
              example:
              - []
    put:
      security:
      - Authorization: []
      tags:
      - Three D Seismic Field Digital Data
      summary: Update a new Three_D_Seismic_Field_Digital_Data data
      description: Update a new Three_D_Seismic_Field_Digital_Data data
      requestBody:
        required: true
        description: Request body to update Three_D_Seismic_Field_Digital_Data data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Three_D_Seismic_Field_Digital_Data'
            example: []
      responses:
        '200':
          description: Three_D_Seismic_Field_Digital_Data data is completely updated
          content:
            application/json:
              example:
                message: The Three_D_Seismic_Field_Digital_Data data is completely
                  updated
    patch:
      security:
      - Authorization: []
      tags:
      - Three D Seismic Field Digital Data
      summary: Update a new Three_D_Seismic_Field_Digital_Data data
      description: Update a new Three_D_Seismic_Field_Digital_Data data
      requestBody:
        required: true
        description: Request body to update Three_D_Seismic_Field_Digital_Data data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Three_D_Seismic_Field_Digital_Data'
            example: []
      responses:
        '200':
          description: one row in Three_D_Seismic_Field_Digital_Data data is updated
          content:
            application/json:
              example:
                message: The one row in Three_D_Seismic_Field_Digital_Data data is
                  updated
    delete:
      security:
      - Authorization: []
      tags:
      - Three D Seismic Field Digital Data
      summary: Delete Three_D_Seismic_Field_Digital_Data data
      description: Delete Three_D_Seismic_Field_Digital_Data data
      responses:
        '200':
          description: Three_D_Seismic_Field_Digital_Data data is deleted
          content:
            application/json:
              example:
                message: The Three_D_Seismic_Field_Digital_Data data was successfully
                  deleted
  /Three-D-Seismic-Field-Digital-Data/{num}:
    parameters:
    - in: path
      name: num
      required: true
      description: number of dummy data to add
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Three D Seismic Field Digital Data Dummy Data
      summary: Add dummy data to Three_D_Seismic_Field_Digital_Data
      responses:
        '200':
          description: add data to Three_D_Seismic_Field_Digital_Data
          content:
            application/json: {}
  /token:
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - User Mgmt
      summary: Login For Access Token
      operationId: login_for_access_token_token_post
      requestBody:
        required: true
        description: Request body to create Three_D_Seismic_Field_Digital_Data AFE
          data
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Body_login_for_access_token_token_post'
            example: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    afe:
      type: array
      items:
        type: object
        properties:
          afe_number:
            type: integer
          workspace_name:
            type: string
          kkks_name:
            type: string
          working_area:
            type: string
          submission_type:
            type: string
          data_type:
            type: string
    Token:
      title: Token
      required:
      - access_token
      - token_type
      - type
      - name
      - expiry_date
      - affiliation
      type: object
      properties:
        access_token:
          title: Access Token
          type: string
        token_type:
          title: Token Type
          type: string
        type:
          $ref: '#/components/schemas/UserType'
        name:
          title: Name
          type: string
        expiry_date:
          title: Expiry Date
          type: string
        affiliation:
          title: Affiliation
          type: string
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    UserType:
      title: UserType
      enum:
      - Administrator
      - Regular User
      - Premium User
      type: string
      description: An enumeration.
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    Body_login_for_access_token_token_post:
      title: Body_login_for_access_token_token_post
      required:
      - username
      - password
      type: object
      properties:
        grant_type:
          title: Grant Type
          pattern: password
          type: string
        username:
          title: Username
          type: string
        password:
          title: Password
          type: string
        scope:
          title: Scope
          type: string
          default: ''
        client_id:
          title: Client Id
          type: string
        client_secret:
          title: Client Secret
          type: string
    Three_D_Seismic_Field_Digital_Data_workspace:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          afe_number:
            type: integer
          Three_d_seismic_field_digital_data_id:
            type: integer
    Three_D_Seismic_Field_Digital_Data:
      type: object
      properties:
        Ba_long_name:
          type: string
        Ba_type:
          type: string
        Area_id:
          type: string
        Area_type:
          type: string
        Acqtn_survey_name:
          type: string
        Start_date:
          type: string
        Shot_by:
          type: string
        Rcrd_rec_length:
          type: string
        Rcrd_rec_length_ouom:
          type: string
        Rcrd_sample_rate:
          type: string
        Rcrd_sample_rate_ouom:
          type: string
        First_seis_point_id:
          type: string
        Last_seis_point_id:
          type: string
        Create_date:
          type: string
        Proc_set_type:
          type: string
        Field_file_number:
          type: string
        Tape_number:
          type: string
        Rcrd_format_type:
          type: string
        Data_store_name:
          type: string
        Original_file_name:
          type: string
        Password:
          type: string
        Digital_size:
          type: string
        Digital_size_uom:
          type: string
        Remark:
          type: string
        Source:
          type: string
        Qc_status:
          type: string
        Checked_by_ba_id:
          type: string
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: v1/token
